import Link from "next/link";

export const metadata = {
  title: 'SchedMusic - Your Music Scheduler',
  description: 'Generated by Next.js',
}

const navLinks = [
  { name: "Register", href:"/register" },
  { name: "Login", href:"/login" },
  { name: "Forgot Password", href:"/forgot-password" },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "darkorange",
            padding: "0.5rem"
          }}>
          {navLinks.map(link => {
            return (
              <Link href={link.href} key={link.name}>
                {link.name}
              </Link>
            );
          })}
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "darkorange",
            padding: "0.5rem"
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}